# Generated by Django 4.2.27 on 2026-01-10 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('iq_test', 'Тест Равена (IQ)'), ('personal_qualities', 'Оценка личностных качеств'), ('productivity', 'Оценка продуктивности')], max_length=50, verbose_name='Тип теста')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_minutes', models.IntegerField(verbose_name='Длительность в минутах')),
                ('questions_count', models.IntegerField(verbose_name='Количество вопросов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_email', models.EmailField(max_length=254, verbose_name='Email соискателя')),
                ('candidate_name', models.CharField(blank=True, max_length=255, verbose_name='Имя соискателя')),
                ('candidate_age', models.IntegerField(blank=True, null=True, verbose_name='Возраст соискателя')),
                ('status', models.CharField(choices=[('pending', 'Ожидает прохождения'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('expired', 'Истек')], default='pending', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало прохождения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение прохождения')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True, verbose_name='Лимит времени (минуты)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия тестирования',
                'verbose_name_plural': 'Сессии тестирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.IntegerField(blank=True, null=True, verbose_name='Сырой балл')),
                ('final_score', models.FloatField(blank=True, null=True, verbose_name='Итоговый балл')),
                ('iq_score', models.IntegerField(blank=True, null=True, verbose_name='IQ балл')),
                ('iq_level', models.CharField(blank=True, max_length=100, verbose_name='Уровень IQ')),
                ('scores_json', models.JSONField(blank=True, default=dict, verbose_name='Баллы по шкалам (JSON)')),
                ('report', models.TextField(blank=True, verbose_name='Текстовый отчет')),
                ('report_json', models.JSONField(blank=True, default=dict, verbose_name='Отчет (JSON)')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tests.testsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса')),
                ('answer_value', models.TextField(verbose_name='Значение ответа')),
                ('series', models.CharField(blank=True, max_length=10, verbose_name='Серия (для IQ теста)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'unique_together': {('session', 'question_number')},
            },
        ),
    ]
