# Generated by Django 4.2.27 on 2026-01-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса')),
                ('question_text', models.TextField(blank=True, verbose_name='Текст вопроса')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='test_questions/', verbose_name='Изображение вопроса')),
                ('series', models.CharField(blank=True, max_length=10, verbose_name='Серия (для IQ теста: A, B, C, D, E)')),
                ('question_type', models.CharField(blank=True, max_length=50, verbose_name='Тип вопроса')),
                ('block_name', models.CharField(blank=True, max_length=100, verbose_name='Название блока (для личностных качеств)')),
                ('correct_answer', models.CharField(blank=True, max_length=10, verbose_name='Правильный ответ')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы тестов',
                'ordering': ['order', 'question_number'],
                'unique_together': {('test', 'question_number')},
            },
        ),
    ]
