# Generated by Django 4.2.27 on 2026-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='answer_options',
            field=models.JSONField(blank=True, default=list, verbose_name='Варианты ответов'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='display_type',
            field=models.CharField(choices=[('radio', 'Одиночный выбор (radio)'), ('checkbox', 'Множественный выбор (checkbox)'), ('textarea', 'Открытый текст (textarea)'), ('number', 'Числовой ответ'), ('select', 'Выпадающий список')], default='radio', max_length=20, verbose_name='Тип отображения'),
        ),
    ]
